### ISSUE TITLE
Window is displayed on a wrong screen

### ISSUE THREAD

**Issue by jsynowiec** [jsynowiec/airqmon#14]
When screens are placed vertically, app windows is always displayed on the most bottom one.

Example display alignment
![screen shot 2018-01-17 at 10 34 39](https://user-images.githubusercontent.com/1029142/35035639-5d9e04da-fb72-11e7-9732-dcaf6d96da9d.png)

Reported by @kdzwinel

**Comment by jsynowiec** [comment]
Related to #1

**Comment by kdzwinel** [comment]
Thanks for opening this issue for me!

Screenshot:

<img width="407" alt="up-down" src="https://user-images.githubusercontent.com/985504/35039951-bad80e04-fb7f-11e7-9a1e-b4b929d4e34e.png">

**Comment by jsynowiec** [comment]
#32

**Comment by jsynowiec** [comment]
This should be resolved thanks to Electron 3 that's included in the v2 of the app. Closing for now.
