### ISSUE TITLE
Preferences shortcut "Cmd + ," hijacks other apps

### ISSUE THREAD

**Issue by thymikee** [jsynowiec/airqmon#17]
This is a **bug** report

While having Airqmon app running in background, whenever I try to access any window's preferences I'm currently focusing with "Cmd + ," shortcut, the Airqmon preferences are being opened. 

Using Airqmon v1.0.0

**Comment by jsynowiec** [comment]
Thanks for reporting 👍

**Comment by thymikee** [comment]
That was quick, thank you!
