### ISSUE TITLE
Migrate to Airly API v2.0

### ISSUE THREAD

**Issue by DCzajkowski** [jsynowiec/airqmon#31]
There has been a new version of the API released. https://www.facebook.com/airlyeu/posts/814768172031664

We should migrate to it before 30.11.2018. I could work on a PR unless someone jumps in before me 😄

**Comment by jsynowiec** [comment]
I'm currently redesigning the API client layer, introducing an intermediate aggregation service that we'll run somewhere (I'm evaluating providers, looking for the free or cheapest one). It'll allow to mitigate the rate limits to some degree and to remove the user-provided API keys (better UX). In future it'll allow to integrate more data providers (very often requested).

**Comment by jsynowiec** [comment]
The new Airly API is supported from v2 onward. The app no longer communicates with the API directly, but through and intermediate caching server. Next version should be released soon.
