### ISSUE TITLE
Wrong location detection

### ISSUE THREAD

**Issue by tweks** [jsynowiec/airqmon#44]
Hey, thanks for developing airqmon, I found it very useful.
The issue which I observe is that sometimes location is wrongly detected. (When I have observed it, I confirmed that other apps use a correct location).
Perhaps it would be useful to add a feature to set a location.

**Comment by jsynowiec** [comment]
What do you mean by _wrongly detected_? Is it different part of the town? Different city? Airqmon doesn't show **your** location, but the closest sensor station.
