### ISSUE TITLE
App icon on menu bar is darkish

### ISSUE THREAD

**Issue by makbol** [jsynowiec/airqmon#46]
I updated system to Mac OS Big Sur. App is working fine except menu bar icon which is quite darkish when the rest of icons are white.

![Zrzut ekranu 2020-11-19 o 16 02 27](https://user-images.githubusercontent.com/5435685/99683434-a3f73600-2a80-11eb-95b9-3f7bb961f408.png)

I tried to update Electron to latest stable version and it seems it fixes the issue. PR is on its way.

**Comment by jsynowiec** [comment]
Thanks. Updating Electron, especially several major versions at once is sometimes tricky due to breaking changes. I already have v11 on my timeline due to Apple Silicon support, but I have to review the Electron changelog and check if it works properly.

**Comment by jsynowiec** [comment]
Issue is related to how Big Sur updates menubar colour based on used wallpaper.

**Comment by jsynowiec** [comment]
@makbol [v2.1.0-beta.1](https://github.com/jsynowiec/airqmon/releases/tag/v2.1.0-beta.1) beta release is now available.

**Comment by makbol** [comment]
@jsynowiec Great! Thanks for releasing version. I installed and seems working fine.
I noticed one minor thing, not sure if related to introduced changes. Readings select is cropped:

![Zrzut ekranu 2020-12-31 o 14 56 06](https://user-images.githubusercontent.com/5435685/03413124-81286900-4b78-11eb-863a-7e83018b6356.png)
